### ISSUE TITLE
kitchen-salt is getting a new owner

### ISSUE THREAD

**Issue by simonmcc** [saltstack/kitchen-salt#101]
@jbussdieker @epcim @ek9 @n-rodriguez @amontalban @milosgajdos83 @corux @azban @malept @mrbobbytables @neillturner @twmartin @jschectman-vs @frots 

A few weeks back Thomas Hatch from SaltStack asked me if I would be interested in moving kitchen-salt under the SaltStack umbrella, so that it becomes an official project sponsored and run by Salt.  I said yes.  As some of you will have been aware, I've been unable to devote time to kitchen-salt, it hasn't been part of my day job for a number of years.  I see this change as kitchen-salt getting stewardship with the resources to keep the project moving forward & stay in sync with the core Salt products.

Daniel Wallace from Salt will be helping with transitioning kitchen-salt under the Salt umbrella.

Thank you for all your help, contributions & patience over the years, I hope the future of kitchen-salt looks brighter from your point of view too.

Simon.

**Comment by gtmanfred** [comment]
I look forward to working with Simon and all of yall to continue the great work here.

**Comment by ssplatt** [comment]
excellent. looking forward to it. thanks for getting the project kicked off and down the road this far.

**Comment by cmarzullo** [comment]
This is great news!

**Comment by scub** [comment]
Woo, exciting stuff.

**Comment by cachedout** [comment]
From the SaltStack community, I want to pass along our sincere thanks to @simonmcc and the community that's worked hard on this project. We're excited to see where kitchen salt can go in the future and we hope that you'll join us in making it even better in the years to come. Thanks!

**Comment by simonmcc** [comment]
To make this transition easy (from a github point-of-view), I'm moving simonmcc/kitchen-salt to kitchen-salt/kitchen-salt & making Daniel an admin of the kitchen-salt org, from there he'll be able to move the project to it's new home in saltstack.
