### ISSUE TITLE
no-chef install script fails with [[: not found

### ISSUE THREAD

**Issue by ssplatt** [saltstack/kitchen-salt#117]
During bootstrap-salt.sh:

```
/tmp/install.sh: 58: /tmp/install.sh: [[: not found
/tmp/install.sh: 59: /tmp/install.sh: [[: not found
sh: 193: Syntax error: end of file unexpected (expecting "fi")
```

https://github.com/saltstack/kitchen-salt/blob/master/assets/install.sh#L58-L59

**Comment by ssplatt** [comment]
this is probably because I'm executing the script in debian, and /bin/sh -> /bin/dash, not /bin/bash.

**Comment by ssplatt** [comment]
https://github.com/saltstack/kitchen-salt/pull/118

**Comment by gtmanfred** [comment]
fixed and releasing in a minute
