### ISSUE TITLE
using salthiera as an external pillar

### ISSUE THREAD

**Issue by mzupan** [saltstack/kitchen-salt#12]
I am looking at your test suite with our setup and so far things are working great with simpe state files. Most of our app state files utilize salthiera with their encryption for compliance reasons. 

https://github.com/gtmtechltd/salthiera

Is there anyway to utilize this in kitchen-salt for pillar lookup?

**Comment by simonmcc** [comment]
I hadn't heard of salthiera until you mentioned it, so there is no support at the moment.

It looks like it should be do-able, but the current salthiera installation process (copy a .py file somewhere special?) feels a little rough and may be tricky to get working across the various salt install methods kitchen-salt offers.
