### ISSUE TITLE
SPM Download failing due to path issue?

### ISSUE THREAD

**Issue by jmickle** [saltstack/kitchen-salt#123]
I am having a bit of trouble figuring out where the issue is on this one. It looks as if SPM tries to download the path but can't due to a salt-master directory of /var/cache/salt/master not being existent? How does salt_solo replicate the salt master?

I, [2017-07-19T17:38:15.093337 #70753]  INFO -- default-ubuntu-1404: Install External Dependencies
I, [2017-07-19T17:38:15.572070 #70753]  INFO -- default-ubuntu-1404: [ERROR   ] An un-handled exception was caught by salt's global exception handler:
I, [2017-07-19T17:38:15.572313 #70753]  INFO -- default-ubuntu-1404: SaltClientError: Could not access /var/cache/salt/master. Path does not exist.
I, [2017-07-19T17:38:15.572896 #70753]  INFO -- default-ubuntu-1404: Traceback (most recent call last):
I, [2017-07-19T17:38:15.573081 #70753]  INFO -- default-ubuntu-1404:   File "/usr/bin/spm", line 12, in <module>
I, [2017-07-19T17:38:15.573277 #70753]  INFO -- default-ubuntu-1404:     salt_spm()
I, [2017-07-19T17:38:15.573435 #70753]  INFO -- default-ubuntu-1404:   File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 487, in salt_spm
I, [2017-07-19T17:38:15.574014 #70753]  INFO -- default-ubuntu-1404:     spm.run()
I, [2017-07-19T17:38:15.574213 #70753]  INFO -- default-ubuntu-1404:   File "/usr/lib/python2.7/dist-packages/salt/cli/spm.py", line 34, in run
I, [2017-07-19T17:38:15.575196 #70753]  INFO -- default-ubuntu-1404:     client.run(self.args)
I, [2017-07-19T17:38:15.575852 #70753]  INFO -- default-ubuntu-1404:   File "/usr/lib/python2.7/dist-packages/salt/spm/__init__.py", line 113, in run
I, [2017-07-19T17:38:15.576032 #70753]  INFO -- default-ubuntu-1404:     self._install(args)
I, [2017-07-19T17:38:15.576172 #70753]  INFO -- default-ubuntu-1404:   File "/usr/lib/python2.7/dist-packages/salt/spm/__init__.py", line 236, in _install
I, [2017-07-19T17:38:15.576310 #70753]  INFO -- default-ubuntu-1404:     self.client = salt.client.get_local_client(self.opts['conf_file'])
I, [2017-07-19T17:38:15.576459 #70753]  INFO -- default-ubuntu-1404:   File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 104, in get_local_client
I, [2017-07-19T17:38:15.576637 #70753]  INFO -- default-ubuntu-1404:     auto_reconnect=auto_reconnect)
I, [2017-07-19T17:38:15.576788 #70753]  INFO -- default-ubuntu-1404:   File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 160, in __init__
I, [2017-07-19T17:38:15.577119 #70753]  INFO -- default-ubuntu-1404:     self.key = self.__read_master_key()
I, [2017-07-19T17:38:15.577311 #70753]  INFO -- default-ubuntu-1404:   File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 193, in __read_master_key
I, [2017-07-19T17:38:15.577346 #70753]  INFO -- default-ubuntu-1404:     self.skip_perm_errors)
I, [2017-07-19T17:38:15.577367 #70753]  INFO -- default-ubuntu-1404:   File "/usr/lib/python2.7/dist-packages/salt/utils/verify.py", line 399, in check_path_traversal
I, [2017-07-19T17:38:15.577388 #70753]  INFO -- default-ubuntu-1404:     raise SaltClientError(msg)
I, [2017-07-19T17:38:15.577407 #70753]  INFO -- default-ubuntu-1404: SaltClientError: Could not access /var/cache/salt/master. Path does not exist.
I, [2017-07-19T17:38:15.577563 #70753]  INFO -- default-ubuntu-1404: Traceback (most recent call last):
I, [2017-07-19T17:38:15.577706 #70753]  INFO -- default-ubuntu-1404:   File "/usr/bin/spm", line 12, in <module>
I, [2017-07-19T17:38:15.577831 #70753]  INFO -- default-ubuntu-1404:     salt_spm()
I, [2017-07-19T17:38:15.578054 #70753]  INFO -- default-ubuntu-1404:   File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 487, in salt_spm
I, [2017-07-19T17:38:15.578223 #70753]  INFO -- default-ubuntu-1404:     spm.run()
I, [2017-07-19T17:38:15.578327 #70753]  INFO -- default-ubuntu-1404:   File "/usr/lib/python2.7/dist-packages/salt/cli/spm.py", line 34, in run
I, [2017-07-19T17:38:15.578352 #70753]  INFO -- default-ubuntu-1404:     client.run(self.args)
I, [2017-07-19T17:38:15.578371 #70753]  INFO -- default-ubuntu-1404:   File "/usr/lib/python2.7/dist-packages/salt/spm/__init__.py", line 113, in run
I, [2017-07-19T17:38:15.578500 #70753]  INFO -- default-ubuntu-1404:     self._install(args)
I, [2017-07-19T17:38:15.578524 #70753]  INFO -- default-ubuntu-1404:   File "/usr/lib/python2.7/dist-packages/salt/spm/__init__.py", line 236, in _install
I, [2017-07-19T17:38:15.578638 #70753]  INFO -- default-ubuntu-1404:     self.client = salt.client.get_local_client(self.opts['conf_file'])
I, [2017-07-19T17:38:15.578724 #70753]  INFO -- default-ubuntu-1404:   File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 104, in get_local_client
I, [2017-07-19T17:38:15.578749 #70753]  INFO -- default-ubuntu-1404:     auto_reconnect=auto_reconnect)
I, [2017-07-19T17:38:15.578768 #70753]  INFO -- default-ubuntu-1404:   File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 160, in __init__
I, [2017-07-19T17:38:15.578900 #70753]  INFO -- default-ubuntu-1404:     self.key = self.__read_master_key()
I, [2017-07-19T17:38:15.578924 #70753]  INFO -- default-ubuntu-1404:   File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 193, in __read_master_key
I, [2017-07-19T17:38:15.579514 #70753]  INFO -- default-ubuntu-1404:     self.skip_perm_errors)
I, [2017-07-19T17:38:15.579556 #70753]  INFO -- default-ubuntu-1404:   File "/usr/lib/python2.7/dist-packages/salt/utils/verify.py", line 399, in check_path_traversal
I, [2017-07-19T17:38:15.579579 #70753]  INFO -- default-ubuntu-1404:     raise SaltClientError(msg)
I, [2017-07-19T17:38:15.580644 #70753]  INFO -- default-ubuntu-1404: salt.exceptions.SaltClientError: Could not access /var/cache/salt/master. Path does not exist.

**Comment by gtmanfred** [comment]
can you provider your kitchen setup so that I can replicate this?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Can you check if this is fixed by 0.0.28?

**Comment by jmickle** [comment]
Confirmed fix sorry for losing track of this ticket!

**Comment by gtmanfred** [comment]
no worries, glad it is working now!
