### ISSUE TITLE
Documentation is gone

### ISSUE THREAD

**Issue by thedrow** [saltstack/kitchen-salt#15]
The wiki used to contain a reference to all configuration options that kitchen-salt provides.
I can't find it anymore.

**Comment by thedrow** [comment]
Oh it's over here now: https://github.com/simonmcc/kitchen-salt/blob/master/provisioner_options.md
Shouldn't the README file link to it?
Why isn't it under the docs folder?

**Comment by simonmcc** [comment]
good point, I'll tidy this up in the new year (or merge your PR with changes ;))

Thank you,

Simon.

**Comment by simonmcc** [comment]
fixed in 21e6bd4e7c4e92c2e2afc96c93fd7bbb5c13c1c5
