### ISSUE TITLE
deprecated python-support package

### ISSUE THREAD

**Issue by Nobbs1337** [saltstack/kitchen-salt#152]
The python-support Package is deprecated, see: https://wiki.debian.org/Python/TransitionToDHPython2

It is used in install.erb:
`  #{sudo('apt-get')} install -y python-support`
The package is not available in Debian Stretch. 
Kitchen converge throws an error message but everything works fine afterwards.
It seems that there are no dependencies from stalt-minion involved.

**Comment by gtmanfred** [comment]
Would you mind submitting a PR for this change?

Thanks,
Daniel

**Comment by ymasson** [comment]
I don't know why python-support is explicitly installed before salt packages, but when you install salt-master or salt-minion :

- Debian wheezy, python-support is installed by dependency 
- Debian jessie, python-support is installed by dependency
- Debian stretch, python-support doesn't exist, but all python dependencies was installed

So, I think we can remove all `#{sudo('apt-get')} install -y python-support` 

If you agree with me, I can submit a PR.

**Comment by gtmanfred** [comment]
that seems fine.

I think it might be legacy from before salt depended on it, but it was still required for using the apt python package.
