### ISSUE TITLE
Minor Version getting stripped off during version check

### ISSUE THREAD

**Issue by qgriffith-zz** [saltstack/kitchen-salt#155]
When installing via yum and setting salt_version to 2106.3.x the check https://github.com/saltstack/kitchen-salt/blob/c489f8d3536dd1dec8996a6a2c81fd22a055102a/lib/kitchen/provisioner/install.erb#L93  is stripping off the .x version so when the comparison is done it thinks the wrong version is installed..

       Complete!
       You asked for 2016.3.7 and you have got 2016.3 installed, dunno how to fix that, sorry!

**Comment by gtmanfred** [comment]
Thanks for for the PR!

Daniel

**Comment by gtmanfred** [comment]
Can you actually give me an example kitchen.yml file so that I can test this?

**Comment by qgriffith-zz** [comment]
I am running kitchen-salt (0.0.28)

Anytime I gave a version with a minor dot release it would think I didn't have the proper version. The FULL_SALT_VERSION is only set to YYYY-MM when the comparison is done

**Comment by gtmanfred** [comment]
As discussed in the PR, this issues is fixed in the master branch already, and I will be working on a release this week, now that I have finished expanding the test suite.

Thanks,
Daniel
