### ISSUE TITLE
salt_copy_filter does not filter files

### ISSUE THREAD

**Issue by dennisfoconnor** [saltstack/kitchen-salt#17]
The salt_copy_filter option is only applied to directories, not individual files.

**Comment by smecsia** [comment]
+1

**Comment by vania-pooh** [comment]
+100500

**Comment by smecsia** [comment]
@simonmcc any updates? When is this going to be released?

**Comment by simonmcc** [comment]
@dennisfoconnor @smecsia @vania-pooh sorry folks, I got side tracked on trying to get some kind of CI & testing running, I'll merge it now.
