### ISSUE TITLE
Data failed to compile for custom salt formulas?

### ISSUE THREAD

**Issue by jmreicha** [saltstack/kitchen-salt#23]
Is there a way to allow the salt provisioner to use custom Salt Stack formula locations?  I am attempting to use a custom formula (sudoers) in my top.sls, but when I pass it through Test Kitchen I receive the following error:

```
local:
           Data failed to compile:
       ----------
           No matching sls found for 'sudoers' in env 'base'
       salt-call exit code: 0
           Data failed to compile:
           No matching sls found for 'sudoers' in env 'base'
       salt-call output grep exit code 0
```

I imagine it just an issue of correctly pointing the `.kitchen.yml` file to my formulas directory?  I have formulas in `/srv/salt/formulas`.

If somebody could point me in the right direction that would be great.

As a workaround I have been able to copy the formula in to the `/srv/salt/` directory and reference it there.  I am new to salt but reading through docs it seems like it is best to separate formulas in to their own directory.

**Comment by simonmcc** [comment]
Sorry for taking so long to respond, it's been a manic few weeks in work!

To your question, yes, there are 2 options open to you for supplying dependent formula, through the dependencies hash or through the vendor_path variable, neither are well documented right now, but there are some notes in the options documentation: https://github.com/simonmcc/kitchen-salt/blob/master/provisioner_options.md

If `/srv/salt/formulas` is already populated, all you should need to do is set `vendor_path` to that:

```
    provisioner:
      vendor_path: /srv/salt/formulas
```

Does that solve this for you?

**Comment by jmreicha** [comment]
@simonmcc Thanks, I somehow missed that option when I was going through the docs originally.

I'm facing a different issue now when trying to test this out.  I am getting the following error when I run a fresh `kitchen converge` after the script adds the gpg key.

`ERROR: You need to allow pip based installations (-P) in order to install the python package 'tornado >= 4.0'`.

Below it has some more clues.

```
sh: 1: salt-call: not found
       No salt-minion installed, install must have failed!!
       salt_install = bootstrap
       salt_url = http://bootstrap.saltstack.org
       bootstrap_options = 
       salt_version = latest
       salt_apt_repo = http://apt.mccartney.ie
       salt_apt_repo_key = http://apt.mccartney.ie/KEY
```

**Comment by jmreicha** [comment]
Just to do some testing I manually used `salt_version: "2015.5.3"` in my configuration (I noticed it was defaulting to 2015.8.6) and got it to work.  This is on Ubuntu 14.04.

**Comment by simonmcc** [comment]
Yeah, I hot that recently, it should be fixed in 0.0.22, which got released over the weekend. I'm away from a laptop for a few days but I think all you need to do to work around it is pass in -P via bootstrap_options to allow pip Python packages until the Deb repos catchup with the new dependency requirements

## 

Simon McCartney
E: simon@mccartney.ie  
M: +44 7710 836 915

**Comment by simonmcc** [comment]
Perfect, I guess that's just before the tornado version got bumped to an un-packaged version

## 

Simon McCartney
E: simon@mccartney.ie  
M: +44 7710 836 915

**Comment by jmreicha** [comment]
@simonmcc Thanks for the info, I tried `salt_bootstrap_options: -P stable` FWIW and had it fail on a different section.  I can post results if you'd like, otherwise I will try upgrading kitchen-salt version.

Thanks again for helping out!

**Comment by simonmcc** [comment]
https://github.com/simonmcc/beaver-formula/blob/test-kitchen/.kitchen.yml#L18-L19 is what I used to get salt installing cleanly

**Comment by jmreicha** [comment]
@simonmcc The config you posted works for me, which I can use as a workaround.  Thanks!
