### ISSUE TITLE
Permission denied on .git files when scp

### ISSUE THREAD

**Issue by arthurzenika** [saltstack/kitchen-salt#242]
```
>>>>>>     Failed to complete #converge action: [scp: /tmp/kitchen/srv/salt/states/.git/objects/cf/1c4f474d22c1b600c9ce0c892b9b9ed49e0790: Permission denied
] on default-bento-centos-7
```

Permissions on those files in my project are 

```
-r--r--r--   1 arthur arthur  421 juin   7 16:34 1c4f474d22c1b600c9ce0c892b9b9ed49e0790
```

With `kitchen-salt-0.2.3.gem`

**Comment by arthurzenika** [comment]
looks like https://github.com/test-kitchen/test-kitchen/issues/544 but this issue is pretty old and I can't find the pre_task in the doc

**Comment by rendler-denis** [comment]
hey. I don't know if you still need this but to fix this you need to set a filter like this:
```
provisioner:
    salt_copy_filter:
      - .git
      - .kitchen
```

**Comment by arthurzenika** [comment]
@rendler-denis thanks! I did solve that problem with `salt_copy_filter`, thanks for you answer.
