### ISSUE TITLE
Feature request: allow more than 1 state to be called in separate salt-call executions

### ISSUE THREAD

**Issue by tkent** [saltstack/kitchen-salt#246]
(Consider this low priority, unless somebody comes out with a better test case)

We have several salt formulas setup like so:

```
{technology}/installed.sls
            /running.sls
            /stopped.sls
            /removed.sls
```

We'd like to use kitchen-salt to test the `removed` and `stopped` states, but can't because there is only one `salt-call` performed. For example, we need `{technology}.running` to be called, *then* `{technology}.removed` to be called in order to test the `{technology}.removed` state.

Today, we have to do that through the shell provisioner, which is quite tedious. It would be great if there was a way to specify a `salt_call_list`.

However, to be fair, we think our formulas that are setup this way are probably uncommon.

**Comment by gtmanfred** [comment]
why not just add both to your state_top?  There is nothing stopping you from just running both, the top file is an ordered list of states to run, so it will run the first one, then the second.

**Comment by tkent** [comment]
@gtmanfred 

Good question! After reading up on salt's state ordering, the issue as I described shouldn't exist. We obviously ran into trouble, so I'll need to chase down why.

However, I did run into another problem that requires the same solution. It's a bit of an edge-case again.

In some cases, our states require salt to reload it's modules and that [doesn't work correctly](https://github.com/saltstack/salt/issues/24925) with the latest version of salt (at least when using `salt-call`). For example, you might have a `docker-ce.imagespresent` state that uses that relies on the dockerng module being loaded, and requires a `docker-ce.installed` state. Today, I can't do that in a  single call to `salt-call` due to the reloading issue.

This is more of a saltstack issue than kitchen-salt, but kitchen-salt could provide a great work around.

**Comment by gtmanfred** [comment]
That is not what that issue is reporting.

If you have a docker-ce.image_present state module, it will absolutely be loaded during the highstate that is run.  salt has been that way forever.

What that issue says is if you have docker-py installed, but you need a newer version of docker installed, reload_modules does not remove the docker import, and import the new version of the docker python library.

But i don't think either of those is a usecase for running multiple commands in  salt.  Plus, you can write a small state module for your tests that just removes the import from python's `sys.modules` so when your dependency gets installed, the new one gets loaded. See https://github.com/saltstack/salt-jenkins/blob/master/_modules/six.py

I am closing this issue.

**Comment by tkent** [comment]
@gtmanfred 

Sorry to bring this back up, but I don't think I communicated clearly. [Here's a test case](https://github.com/tkent/kitchen-salt-12) you can quickly use to verify what I'm talking about. And I'll try to be a bit more clear :-).

> If you have a docker-ce.image_present state module, it will absolutely be loaded during the highstate that is run. salt has been that way forever.

There's no confusion about wether or not SLSs included in a high state will be evaluated, or wether or not state modules will be loaded. I'm sorry if I gave that impression.

> What that issue says is if you have docker-py installed, but you need a newer version of docker installed, reload_modules does not remove the docker import, and import the new version of the docker python library.

Yes, it certainly does. I copied and pasted the wrong link! I meant to [link this issue](https://github.com/saltstack/salt/issues/35455). I had both up and didn't realize I pasted the wrong one.

The fix for this issue was merged back in 2017 and the specific error I'm encountering is different. However, the symptom is nearly identical. You have to restart the salt minion for everything to work correctly, because some part of the module reloading process doesn't work. If you check the referenced repository, you'll be able to pretty quickly validate this yourself.

> But i don't think either of those is a usecase for running multiple commands in salt. Plus, you can write a small state module for your tests that just removes the import from python's 

We might look at that as a work around! But to be clear,  the use case for multiple state calls is to avoid needing to build workarounds.

The example I included is certainly caused by some bug in a saltstack module (or some module it depends on), but cases like these show up frequently. Having the ability to use multiple salt-call executions would free people building testing from needing to chase them down each time they show up.

**Comment by tkent** [comment]
@gtmanfred just a quick reminder if you could take a look at my note.
