### ISSUE TITLE
Prepare command for lxd driver

### ISSUE THREAD

**Issue by dgengtek** [saltstack/kitchen-salt#247]
I have been using kitchen-salt (0.2.3) with kitchen-lxd_sling (0.5.5) and kitchen-salt would fail when passing the provisioning command to the lxd driver which uses lxc exec to pass the commands to the container.

`lxc-execute {-n name} [-d] [-f config_file] [-s KEY=VAL] [-- command]`

The binary is not using a shell by default and is unable to handle the globs and chained commands. I am wondering in which plugin this issue should be best raised and handled?

I am using the following patch to make it temporarily work. Note I have no clue about ruby and did not make sure how this patch interacts with any other drivers.

```
--- salt_solo.rb	2018-06-17 15:06:14.571628197 +0200
+++ salt_solo.rb	2018-06-17 15:06:02.995017672 +0200
@@ -110,9 +110,11 @@
       def prepare_command
         cmd = ''
         unless windows_os?
+          cmd << "sh -c '"
           cmd += <<-CHOWN
             #{sudo('chown')} -R "${SUDO_USER:-$USER}" "#{config[:root_path]}/#{config[:salt_file_root]}"
           CHOWN
+          cmd << "'"
         end
         if config[:prepare_salt_environment]
           cmd += <<-PREPARE
@@ -257,6 +259,7 @@
           salt_config_path = config[:salt_config]
           cmd << "(get-content #{os_join(config[:root_path], salt_config_path, 'minion')}) -replace '\\$env:TEMP', $env:TEMP | set-content #{os_join(config[:root_path], salt_config_path, 'minion')} ;"
         else
+          cmd << "sh -c '"
           # install/update dependencies
           cmd << sudo("chmod +x #{config[:root_path]}/*.sh;")
           cmd << sudo("#{config[:root_path]}/dependencies.sh;")
@@ -273,6 +276,7 @@
           cmd << ' --retcode-passthrough'
         end
         cmd << ' 2>&1 ; exit $LASTEXITCODE' if windows_os?
+        cmd << "'"
         cmd
       end
```

Thanks for any input

**Comment by gtmanfred** [comment]
I would say it should be an option on the lxc driver, to tell it that you want to use a shell to execute your commands.

**Comment by dgengtek** [comment]
Makes sense. Thanks
