### ISSUE TITLE
hardcoded directory/file references

### ISSUE THREAD

**Issue by ghost** [saltstack/kitchen-salt#259]
pillars.rb has hard coded links such as:
sandbox_pillar_path = File.join(sandbox_path, '/srv/pillar') 
top_file = File.join(config[:local_salt_root], 'salt/top.sls')

The top file we have is in salt/state/top.sls so top_file doesn't work.
/srv/pillar is wrong for us as we use /srv/salt/pillar

I may be missing some config options but it was basically easier to change the code to reference
config[:pillar_sub_dir]
sandbox_pillar_path = File.join(sandbox_path, config[:pillar_sub_dir])
and similar for top_file.
 
for the minion config that is created:
kitchen/provisioner/minion.erb
file_roots:
 <%= config[:salt_env] %>:
   - <%= os_join(config[:root_path], config[:salt_file_root]) %>
   - <%= os_join(config[:root_path], config[:salt_spm_root], 'salt') %>

in this case I had to add config[:salt_state_subdir] # is equal to state.
That's my penny's worth.

**Comment by gtmanfred** [comment]
If you are using something different from the defaults, then you would be better off writing your own custom minion template to better represent your environment.

https://kitchen.saltstack.com/docs/file/docs/provisioner_options.md#salt_minion_config_template

set the file_roots to match what you need for /srv/salt/states and then the pillar roots to /srv/salt/pillar.
