### ISSUE TITLE
gpg.sh causing issues in Fedora

### ISSUE THREAD

**Issue by dubb-b** [saltstack/kitchen-salt#265]
I have not been able to track down this gpg issue. It seems to have come in during the addition of gpg rendering for kitchen salt.

Here is the log I get:

 sudo: /tmp/kitchen/gpgkey.sh: command not found
04:47:16        [ERROR   ] An un-handled exception was caught by salt's global exception handler:
04:47:16        KeyError: 'saltutil.is_running'
04:47:16        Traceback (most recent call last):
04:47:16          File "/usr/bin/salt-call", line 11, in <module>
04:47:16            salt_call()
04:47:16          File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 396, in salt_call
04:47:16            client.run()
04:47:16          File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
04:47:16            caller.run()
04:47:16          File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
04:47:16            ret = self.call()
04:47:16          File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 204, in call
04:47:16            ret['return'] = func(*args, **kwargs)
04:47:16          File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 860, in highstate
04:47:16            conflict = _check_queue(queue, kwargs)
04:47:16          File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 250, in _check_queue
04:47:16            conflict = running(concurrent=kwargs.get('concurrent', False))
04:47:16          File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 209, in running
04:47:16            active = __salt__['saltutil.is_running']('state.*')
04:47:16          File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1121, in __getitem__
04:47:16            func = super(LazyLoader, self).__getitem__(item)
04:47:16          File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 101, in __getitem__
04:47:16            raise KeyError(key)
04:47:16        KeyError: 'saltutil.is_running'
04:47:16        Traceback (most recent call last):
04:47:16          File "/usr/bin/salt-call", line 11, in <module>
04:47:16            salt_call()
04:47:16          File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 396, in salt_call
04:47:16            client.run()
04:47:16          File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
04:47:16            caller.run()
04:47:16          File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 134, in run
04:47:16            ret = self.call()
04:47:16          File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 204, in call
04:47:16            ret['return'] = func(*args, **kwargs)
04:47:16          File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 860, in highstate
04:47:16            conflict = _check_queue(queue, kwargs)
04:47:16          File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 250, in _check_queue
04:47:16            conflict = running(concurrent=kwargs.get('concurrent', False))
04:47:16          File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 209, in running
04:47:16            active = __salt__['saltutil.is_running']('state.*')
04:47:16          File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1121, in __getitem__
04:47:16            func = super(LazyLoader, self).__getitem__(item)
04:47:16          File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 101, in __getitem__
04:47:16            raise KeyError(key)
04:47:16        KeyError: 'saltutil.is_running'

Any help would be appreciated or a hint to where I may be missing.

https://jenkinsci.saltstack.com/job/2017.7/job/salt-fedora-27-py2/5/console

It seems to be during the git.salt states, not sure where.

@gtmanfred any advice is welcome.

**Comment by gtmanfred** [comment]
Best guess is that `gpg` is not installed?

You can install it your bootstrap command by adding `-p gnupg`.

Though it shouldn't be needed, since we only run gpg commands if the gpg key is specified for .kitchen.yml.

https://github.com/saltstack/kitchen-salt/blob/master/lib/kitchen/provisioner/gpgkey.erb#L7

Message me on slack if that doesn't fix it.

**Comment by gtmanfred** [comment]
yeah, that file shouldn't exist if unless `gpg_key` is set.

https://github.com/saltstack/kitchen-salt/pull/263/files#diff-b073374b9e55fed9a2f13c968763ff73R325

What does your .kitchen.yml look like?

**Comment by dubb-b** [comment]
Looks like it is futures. It was looking for concurrent import.

Thanks for looking either way.
