### ISSUE TITLE
No color

### ISSUE THREAD

**Issue by rgarrigue** [saltstack/kitchen-salt#279]
Hello

I'm trying to get my whole `kitchen test` without color so our Jenkins logs is readable. 

- I added `-n` to salt bootstrap script options
- I added color: false to my pytest.ini (using testinfra as verifier)
- I'm running `kitchen test --no-color`

Last thing is salt_solo, you've an option to force colored output on, but no option to disable it. Can you add that ?

Moreover, I'ld suggest "inheriting" kitchen `--color / --no-color` for the default value (and maybe to add `-n` or not to bootstrap option). 

Best regards,

**Comment by daks** [comment]
Just for your information, we use this option
```
        wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'xterm']) {
```
in our Jenkinsfile so that output colors are rendered and readable :)

It may needs a Jenkins plugin though.

**Comment by bryceml** [comment]
This issue can be closed now that we're currently using travis-ci since the colors don't mess up the output.
