### ISSUE TITLE
Unable to mock 'mine. get' in a saltstack custom module.

### ISSUE THREAD

**Issue by rukundofiston** [saltstack/kitchen-salt#282]
In my custom state, I have something like this 

> mine_data=__salt__ ['mine. gets'] ('*', 'key'),

When testing with kitchen I'm unable to mock this mine, so the test fails.
Any suggestion or workaround?

The custom state run well in my local environment.

Thank you

**Comment by daks** [comment]
really interesting question, we face the same problem and ignore mine in our tests, but mocking it could be a solution

**Comment by gtmanfred** [comment]
You would need to move to testing your module in a regular test suite, using `pytest-salt`, check out how it is used in <https://github.com/saltstack/pepper> to make a fake salt environment with multiple minions.

This isn't really something that can be done in kitchen until multinodes is supported 

https://github.com/chef/chef-rfc/blob/master/rfc084-test-kitchen-multi.md
