### ISSUE TITLE
Adapt for `test-kitchen 2.0.0`

### ISSUE THREAD

**Issue by myii** [saltstack/kitchen-salt#285]
As mentioned in the Slack group for SaltStack-Formulas, we've faced broken builds for the last few days.  Tracking this down led to the release of `test-kitchen 2.0.0` a few days back.  Fixed with https://github.com/saltstack-formulas/template-formula/pull/81, with the comment there explaining the background in more detail.

**Comment by myii** [comment]
Resolved by 1523d3ca435c27b940971f052f0c782dd72dcd74.

**Comment by myii** [comment]
@gtmanfred `0.6.0` hasn't been added to the [releases](https://github.com/saltstack/kitchen-salt/releases) page, though.

**Comment by gtmanfred** [comment]
tag pushed
