### ISSUE TITLE
salt-call: command not found in kitchen-salt 0.6.2

### ISSUE THREAD

**Issue by B1ue-W01f** [saltstack/kitchen-salt#306]
I've a working setup with the below version combination on linux:

ruby 2.7
test-kitchen 2.4.0
inspec 4.18.104
kitchen-inspec 1.3.1
kitchen-salt 0.6.0
kitchen-vagrant 1.6.1

However, after my kitchen-salt updated to 0.6.2 I get the below error code:
```
sudo: salt-call: command not found
```

There's little I can find useful to debug in the logs but I've noticed that the salt bootstrap process does not appear to occur - it just completely skips over it in the terminal output.

**Comment by kiemlicz** [comment]
I think this is the workaround:  
`install_after_init_environment: true` (or use `pip` installation)
And this is the breaking change:
```
      def install_command
        return unless config[:salt_install]
        unless not config[:salt_install] == 'pip' || config[:install_after_init_environment]       <-------
          setup_salt
        end
      end
```
However I'm not ruby dev to build and confirm it 100% 
Use the workaround if potential side effects won't hit you

**Comment by ymasson** [comment]
Same error with 0.6.2.

@s0undt3ch 
no release and tag for this version ?

**Comment by daks** [comment]
I'm hitted by the same bug. It comes from commit b6a584440d8a4aba4bb0f9813f14458f9473b77a and it's present in 0.6.2 but not 0.6.1.

`config['salt_install']` has been removed from the line
```
        unless not config[:salt_install] || config[:salt_install] == 'pip' || config[:install_after_init_environment]
```
I have `salt_install: apt` set.
