### ISSUE TITLE
Travis CI failures since June 2020

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/kitchen-salt#321]
Earlier this year, it looks like the Travis CI pipeline started failing across all platforms:
- For Debian/Ubuntu systems, this looks related to dropping Python 2 support since `3001` was released.
- For CentOS, I see quite a few Python 2 references still happening, and think it is probably related to the same problem. Though, I can't quite tell why, but the following error consistently occurs over there:

https://travis-ci.com/github/saltstack/kitchen-salt/jobs/459005243#L2086

**Comment by bryceml** [comment]
fixing here: https://github.com/saltstack/kitchen-salt/pull/322
