### ISSUE TITLE
Amazon Linux 1 salt install moved

### ISSUE THREAD

**Issue by olhado** [saltstack/kitchen-salt#325]
It appears that salt moved older Linux distributions to archive.repo.saltstack.com. This includes Amazon Linux 1.

I am not sure how to properly tell the install.sh to use the new URL: https://archive.repo.saltstack.com/yum/amazon/latest/x86_64/latest/

**Comment by bryceml** [comment]
if by install.sh you mean the bootstrap script, you add `-R archive.repo.saltstack.com` as a bootstrap arg

**Comment by olhado** [comment]
What parameter do I pass that in through? I’m not seeing an obvious spot for it in the test-kitchen provisioner option.

**Comment by bryceml** [comment]
https://github.com/saltstack/kitchen-salt/blob/master/lib/kitchen/provisioner/salt_solo.rb#L61

https://github.com/saltstack/kitchen-salt/blob/master/.kitchen.yml#L19

 salt_bootstrap_options

**Comment by olhado** [comment]
Well, _that's_ embarrassing. Thanks for the heads up.
