### ISSUE TITLE
Outdated Gem version 

### ISSUE THREAD

**Issue by streambinder** [saltstack/kitchen-salt#330]
Since latest release (at the time of writing, `0.7.0`), the Gem version hasn't been updated in the `kitchen-salt.gemspec` to reflect the release created on Github, implying also that [latest release on rubygems.org](https://rubygems.org/gems/kitchen-salt) still is `0.6.3`.

**Comment by awerner** [comment]
Is there any plan on releasing the 0.7.0 soon? The support for `_utils` is quite curcial for me.
