### ISSUE TITLE
Windows vagrant box directory creation fails

### ISSUE THREAD

**Issue by PatOShea** [saltstack/kitchen-salt#36]
Hi, I'm really looking forward to using this busser.  We really need windows support and have just started looking at using kitchen-salt.  Here's our current error when trying to download the chef omnibus package. 

```
-----> Converging <default-windows-2012r2>...
       Preparing files for transfer
       Preparing salt-minion
       Preparing state_top
       Preparing pillars into /srv/pillar
       Preparing formula: beaver from C:/kitchen-salt-tutorial/beaver-formula
$$$$$$ Remove-Item : A parameter cannot be found that matches parameter name 'rf'.
$$$$$$ At line:1 char:4
$$$$$$ + rm -rf $env:TEMP\kitchen ; mkdir -p $env:TEMP\kitchen
$$$$$$ +    ~~~
$$$$$$     + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBin
$$$$$$    dingException
$$$$$$     + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Comm
$$$$$$    ands.RemoveItemCommand
$$$$$$
$$$$$$ mkdir : Parameter cannot be processed because the parameter name 'p' is
$$$$$$ ambiguous. Possible matches include: -Path -PipelineVariable.
$$$$$$ At line:1 char:34
$$$$$$ + rm -rf $env:TEMP\kitchen ; mkdir -p $env:TEMP\kitchen
$$$$$$ +                                  ~~
$$$$$$     + CategoryInfo          : InvalidArgument: (:) [mkdir], ParameterBindingEx
$$$$$$    ception
$$$$$$     + FullyQualifiedErrorId : AmbiguousParameter,mkdir
>>>>>> Converge failed on instance <default-windows-2012r2>.
>>>>>> Please see .kitchen/logs/default-windows-2012r2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [rm -rf $env:TEMP\kitchen ; mkdir -p $env:TEMP\kitchen]
>>>>>> ----------------------
C:\kitchen-salt-tutorial\beaver-formula [master +0 ~1 -0]
```

**Comment by PatOShea** [comment]
Issue was installing ChefDK instead of just the Chef Client. The directory structure differs slightly. Hopefully others understand that "omnibus installer" is just the client. I'll submit a PR for updating the instructions.

**Comment by simonmcc** [comment]
@PatOShea kitchen-salt rather lazily uses the chef omnibus package to get a working install of ruby & a few other bits on the guest VM, so that kitchen will run, it's been on the todo list since I started kitchen-salt, I think the folks over in kitchen-puppet have worked out a clean way of getting enough ruby & busser stuff on the guest vm without needing all of  the chef omnibus install, I just haven't got around to pulling it into kitchen-salt.

**Comment by gtmanfred** [comment]
@PatOShea does this fix your problem?

https://github.com/saltstack/kitchen-salt/pull/50

Thanks,
Daniel
