### ISSUE TITLE
Mkdir: File Exists error during 

### ISSUE THREAD

**Issue by DrMerlin** [saltstack/kitchen-salt#37]
-----> Starting Kitchen (v1.5.0)
-----> Converging <default-ubuntu-1204>...
       Preparing files for transfer
       Preparing salt-minion
       Preparing state_top
       Preparing pillars into /srv/pillar
       Preparing formula: beaver from /home/<name>/ksalt-tut/beaver-formula
       Preparing formula: beaver from /home/<name>/ksalt-tut/beaver-formula/
       Preparing formula: README.md from /home/<name>/ksalt-tut/beaver-formula/
       Preparing formula: test from /home/<name>/ksalt-tut/beaver-formula/
Preparing formula: top.sls from /home/<name>/ksalt-tut/beaver-formula/

> > > > > > ------Exception-------
> > > > > > Class: Kitchen::ActionFailed
> > > > > > Message: Failed to complete #converge action: [File exists - /tmp/<name>/default-ubuntu-1204-sandbox-20160224-2200-p4ul3l/srv/salt/top.sls]

I get this error when trying to bring up the default beaver formula.  

I edited salt_solo.rb:375 to read:
`FileUtils.mkdir_p(formula_dir) unless File.exists?(formula_dir)`

And it works now.  Not sure why it was crashing there for me to begin with- especially since it didn't crash there for my co-worker doing essentially the same thing.

Is this a harmless change to prevent my error?

**Comment by cmarzullo** [comment]
Think this is the same as the #47 I use kitchen-salt pretty regular with home grown formulas and don't run into this issue. Perhaps the boxes he's linking to are old or something. I've been using the bento boxes from ops code and a simple python module to generate formula scaffolding: https://github.com/cmarzullo/saltscaffold

**Comment by gtmanfred** [comment]
Can you provide me with a box to test with so that I can replicate this issue?

Thanks,
Daniel

**Comment by DrMerlin** [comment]
I'll see what I can dig up.  It's been 18 months since I opened this.

**Comment by gtmanfred** [comment]
Sorry about that, Recently we (SaltStack Inc.) have taken over kitchen-salt, and I am working on cleaning up the open issues.

Helping replicate this would be greatly appreciated.

Thanks for your help!

**Comment by DrMerlin** [comment]
I love that you're taking over kitchen-salt, and I'll do what I can to pitch in.

**Comment by gtmanfred** [comment]
@DrMerlin were you able to replicate this again?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Closing, since we have been unable to replicate this.  If you come back to it, please let me know and I can reopen, or open a new issue with more information about replicating.

Thanks!
Daniel
