### ISSUE TITLE
Verify fails on windows with serverspec busser

### ISSUE THREAD

**Issue by PatOShea** [saltstack/kitchen-salt#39]
I'm trying to do basic serverspec testing on a windows vagrant VM, but the busser appeard to be breaking.. [Here](https://gist.github.com/PatOShea/923e9a61982362e09104) are the logs and [diagnose](https://gist.github.com/PatOShea/700c3dd2348aba6c5923) output. It looks like the & prefix is being encoded, but I'm not sure. Is this a kitchen-salt issue, or test-kitchen in general?

I can tell you the path is correct after manually inspecting the box.Although Pester is a workaround, but we want to use the same tool across platforms.

**Comment by PatOShea** [comment]
Looks like this is an issue with chefdk or test-kitchen. https://github.com/test-kitchen/test-kitchen/issues/964

**Comment by simonmcc** [comment]
This might help: 

## http://hedge-ops.com/tutorial-for-test-kitchen-with-azure/

Simon McCartney
E: simon@mccartney.ie  
M: +44 7710 836 915
