### ISSUE TITLE
Should PRs go to the kitchen-salt organization?

### ISSUE THREAD

**Issue by PatOShea** [saltstack/kitchen-salt#40]
Simon, I'm hoping to help my organization and others use kitchen-salt with windows and submitted a PR recently here. Should it go here (kitchen-salt/kitchen-salt) instead? I assume you created that for sharing the management of kitchen-salt. Is that right? It does seem like that fork is behind your repo. Thanks again for sharing this work. It's going to help our immensely.

**Comment by simonmcc** [comment]
@PatOShea you're right, kitchen-salt/kitchen-salt was setup to make it easier to give more community control to kitchen-salt (as it's no longer part of my day job, my org has moved on to ansible for various reasons...) @milosgajdos83 & @johanek & myself have control over the kitchen-salt/kitchen-salt project, but we never got round to actually making it the official repo, so the infrequent releases have continued to come from simonmcc/kitchen-salt, making PR's & raising issues against simonmcc/kitchen-salt is the right place for now.  I'm delighted you're finding kitchen-salt useful, I'll try and help where I can!

**Comment by neillturner** [comment]
Hope you don't mind me passing comment but I would suggest you drop kitchen-salt/kitchen-salt and stick to this one. What i have done with kitchen-puppet is there are 2 others who have merge privilege and can review issues/PRs - maybe you can ask if anyone else who is using salt wants to help. I still build new releases for kitchen-puppet but others can do alot of the other stuff. 

@simonmcc i hope your using my kitchen-ansible plugin now -). 

I'm about to start a contract that uses salt but they are reviewing usage and i'll suggest they move to ansible as it easier to find folks with ansible experience than salt experience even if salt maybe the superior product. 

Sorry folks the rightscale state of devops report showed than ansible is twice as popular as salt 
http://www.rightscale.com/blog/sites/default/files/respondents-using-devops-tools.png

**Comment by gtmanfred** [comment]
We have now moved the kitchen-salt plugin to the saltstack organization.

I am closing this issue.
