### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by corux** [saltstack/kitchen-salt#45]
Would it be possible to release a new version (0.0.23)?
Especially with regard to #43 and the test-kitchen 1.7.0 release.

**Comment by justyns** [comment]
Agreed, I just ran into the bug from #43 as well and would appreciate a release

**Comment by simonmcc** [comment]
0.0.23 just released :) https://rubygems.org/gems/kitchen-salt/versions/0.0.23  Thank you folks!
