### ISSUE TITLE
Allow to specify salt version to be installed

### ISSUE THREAD

**Issue by thedrow** [saltstack/kitchen-salt#6]
salt-bootstrap should be installed with the latest version unless specified otherwise.
We still provision with the develop branch sometimes due to exceptions within Salt.

**Comment by simonmcc** [comment]
There's already support to do that via the salt_bootstrap_options on the provisioner, by default we install the latest stable via git (i.e. exactly what bootstrap.saltstack.org does), you can pass options to the bootstrap script to get it to do whatever you want, for example:

```
- name: use-development-branch-salt
  provisioner:
    salt_bootstrap_options: -M -N git develop
```

Will install from the develop branch.  You can see more if the installer options here: https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L180

Does that do what you need?

**Comment by thedrow** [comment]
Yea, exactly!
It should be documented somewhere.

**Comment by simonmcc** [comment]
it is now :) 

https://github.com/simonmcc/kitchen-salt/blob/master/provisioner_options.md#salt_bootstrap_options
