### ISSUE TITLE
Using other formulas.

### ISSUE THREAD

**Issue by alfredopalhares** [saltstack/kitchen-salt#7]
I have a simple formula (now) that depends on the build-essential.

How do you had external formulas with replicating code and testing the formula without any ugly hacks?
## 

Regards,
Alfredo Palhares

**Comment by simonmcc** [comment]
This is something I'm trying to think through.  Salt currently has no metadata about dependencies, and therefore no tooling at all for resolving dependencies (eg librarian-puppet or Berkshelf).  

We're currently working on a tool called gitshelf, which is supposed to be a light weight tool for managing a collections of git repos.  https://github.com/moniker-dns/gitshelf is a work in progress, but it allows you to describe the layout of an arbitrary collection of git repos & symlinks in yaml & have the tool install them for you, and optionally create a tarball off that collection to be used a deployment artefact. 

How would you like to describe the dependent formula? is this something that should be expanded into  metadata about your formula?  Something you would encode in your .kitchen.yaml?  drop a gitshelf.yaml into your formula?

**Comment by simonmcc** [comment]
[v0.0.18](https://github.com/simonmcc/kitchen-salt/releases/tag/v0.0.18) allows your repo/project to contain multiple formula or state collection, how you gather that collection is still up to you.

**Comment by mzupan** [comment]
sorry to reply to this

but whats the syntax for multiple formulas.. it seems just doing like

```
formula:
  - state1
  - state2
```

just iterate over that since I control the testing.
