### ISSUE TITLE
outdated serverspec docs

### ISSUE THREAD

**Issue by azban** [saltstack/kitchen-salt#71]
https://github.com/simonmcc/kitchen-salt/blame/master/INTRODUCTION.md#L200 shows an outdated and suboptimal way to use serverspec

from: https://github.com/test-kitchen/busser-serverspec#-notice

> You should use Kitchen::Verifier::Shell + Serverspec instead of Busser::RunnerPlugin::Serverspec.

usage example: https://github.com/cl-lab-k/apache2-take/blob/shell_verifier/.kitchen.yml#L20

would you like me to update the README? is there any reason why we shouldn't move towards this? i would also like to deprecate the chef install to make people aware that this is a preferred option.

spent a few hours dancing around with this, and wanna make it more clear for new people coming into the project

**Comment by simonmcc** [comment]
I'd love to see the need for a Chef install to go away, and I think @neillturner has that working in his kitchen-puppet & kitchen-ansible plugins.  As for changing the method used to call serverspec, I don't really understand what you want to change, the new preferred method isn't clear to me.  @jbussdieker might have stronger opinions on this, I'm not actively developing kitchen-salt at the moment.

**Comment by jbussdieker** [comment]
I've mostly used inspec with an ami that has salt preinstalled and an empty folder at /opt/chef. This is not ideal for users wishing to use vanilla amis so I like the idea. I'm a bit swamped now but will hopefully have time to review this in the next few days.

**Comment by azban** [comment]
@simonmcc like you said, further removing the need for Chef is the main win we get.. as well as more control over serverspec/Rspec. you get to set up the ruby environment as you wish as it is on the host, and use the SSH capabilities of serverspec which removes the need to install chef all together (or be sneaky and install ruby at /opt/chef/embedded/)... at the end of the day, busser-serverspec is deprecated and unsupported so relying on it is dangerous at best.

@jbussdieker no worries and no rush.. if you are down for this approach, i'll submit a PR with documentation changes, and deprecation warnings.

fwiw, [here](https://gist.github.com/jedipi/7e0e5ae9db4e66243cc06ec3128abb35) is a rough changeset given the new method if you only need serverspec (after deprecation, i.e. new major version).. it's not totally perfect because it doesn't play well with setups are relying on serverspec and busser, but if you'd like, i can take a quick dive into making busser work without a chef install (or mocking /opt/chef/..), i'm not a big fan of the approach [https://github.com/simonmcc/kitchen-salt/commit/1e23e01cea8db02561811fd4088aeb1f0044246e](here) because it muddles global ruby state. is there a reason why we don't want to install rvm (get.rvm.io is already framework agnostic), into the sandbox path and then install a version of ruby to use there and set that as the ruby_bin_path? it would simplify things a lot also.. looks more like 

```
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
\curl -sSL https://get.rvm.io | bash -s -- --ignore-dotfiles --path sandbox_path/rvm --ruby --gems=bundle
```

**Comment by neillturner** [comment]
i have a new plugin kitchen-verifier-serverspec   https://github.com/neillturner/kitchen-verifier-serverspec which doesn't need busser or chef and can even run just from your workstation. I'm getting a few downloads of this so it useful. It also lets you put the serverspec tests where ever you want rather than forcing you to put them in test/integration ....

 I'm not doing much development of my kitchen-ansible or kitchen-puppet as they are pretty mature now, i'm mostly just merging in contributions and then testing and doing releases. it doesn't take too much time. 

It would be great if the kitchen-salt PRs could be merged or rejected.  As you code is probably fairly mature now and just needs to be maintained.  Thanks for merging my PR.

**Comment by gtmanfred** [comment]
These have been removed.  I still need to sit down and add some more back in, but I think that the getting started is good enough to close this.

Thanks,
Daniel
