### ISSUE TITLE
support for git repo that is /srv

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/kitchen-salt#76]
It would be great to have a way to specify what the root is in the git repository

In my states https://github.com/gtmanfred/blog-sls i have states and pillars, i want to overwrite the pillars, but it would be great to say that /salt/ should be dropped in /tmp/kitchen/srv/salt, instead of having to put the .kitchen.yml in the salt/ directory instead.

Thanks
Daniel

**Comment by ek9** [comment]
I belive you can accomplish this by tweaking the configuration options of `kitchen-vagrant` driver. It allows you to set different configuration options for your vagrant file. In your case this would be:

```yaml
driver:
  name: vagrant
  synced_folders:
    - ["salt", "/tmp/kitchen/srv/salt"]
```

You can find more information on supported config parameters on `kitchen-vagrant` driver page: https://github.com/test-kitchen/kitchen-vagrant#-configuration

Suggesting to close this.

**Comment by gtmanfred** [comment]
Unfortunately I am using kitchen-docker, which doesn't appear to have a similar option.

https://github.com/test-kitchen/kitchen-docker

**Comment by gtmanfred** [comment]
I can add

```
volumes:
  - $PWD:/tmp/kitchen/srv/salt
```

But the salt directory is removed first before trying to put everything in places, so this still fails.

**Comment by gtmanfred** [comment]
I am closing this issue in favor of #92 which contains more information.

**Comment by gtmanfred** [comment]
For the record, anyone that gets to this.

There is a, possibly still, undocumented config option called `local_salt_root`, if your git repo is like your `/srv` then you can set `local_salt_root: '.'` and it will tack on `salt` to that, and copy that to `/tmp/kitchen/srv/salt`

A more robust version of this is still going to need to be worked on in #92
