### ISSUE TITLE
Mock pillar data.

### ISSUE THREAD

**Issue by alfredopalhares** [saltstack/kitchen-salt#8]
Hello can we mock pillar data from the kitchen yaml file?

**Comment by simonmcc** [comment]
Yes you can, you can declare the pillars in .kitchen.yaml (https://github.com/simonmcc/kitchen-salt/blob/master/docs/provisioner.md#pillars) or have them loaded from an external file (for a pillar.example file, for example: https://github.com/simonmcc/kitchen-salt/blob/master/docs/provisioner.md#pillars-from-files)
