### ISSUE TITLE
salt_apt_repo in provisioner/salt_solo.rb does not exist

### ISSUE THREAD

**Issue by daks** [saltstack/kitchen-salt#82]
Hello,

in kitchen/provisioner/salt_solo.rb, we can see
```
        salt_apt_repo: 'http://apt.mccartney.ie',
        salt_apt_repo_key: 'http://apt.mccartney.ie/KEY',
```
which does not exist.
I think we can use http://repo.saltstack.com/

**Comment by ek9** [comment]
I did a PR ( #89 ) that would address this.

**Comment by daks** [comment]
Seems good to me if Ubuntu is the default image used, this apt repo is the good one.
