### ISSUE TITLE
Way to define states from files, like for pillars

### ISSUE THREAD

**Issue by daks** [saltstack/kitchen-salt#83]
You can define pillars-from-files, which is quite convenient. Ability to do this for states could be great.

**Comment by ek9** [comment]
There is `state_top_from_file` which is exactly for this:
https://github.com/simonmcc/kitchen-salt/blob/master/provisioner_options.md#state_top_from_file

**Comment by daks** [comment]
I saw state_top_from_file but I'm not sure I can do what I want with it. 
I want to test my usersandgroups formula (github.com/daks/usersandgroups-formula), and to test removal of users, I need to first create some, so I need to define a top file (I can with this) but I also need another state, and I can't define it, or didn't find how.
Another point is: maybe (I'm not sure about that) I can define it in the kitchen.yml file, but as I want to define several scenarii, this file will soon become very complicated, so I prefer to have both states and pillars in external files. This way, I can have have one foo test profile (with states/pillars and my inspec tests), and another bar profile,...

**Comment by cmarzullo** [comment]
@daks, when I run into a testing situation like that I build some 'mockup' in my formula. where I use a mockup/init.sls to do random stuff. Stuff that will prepare the system. Like sometimes I need SSL certificates for my elasticsearch formula. I run mockup.sls just for specific test suites.

**Comment by ek9** [comment]
The mockup solution seems like a standard way of accomplishing this.

For several / separate scenarios you can define different `suites` in `.kitchen.yml`.

**Comment by daks** [comment]
I would like to have a "clean" formula, which only contains the code that it needs. I think adding a "mockup" part may confuse someone who wants to read the code, and understand what it does.
In my opinion _(but I may be wrong)_, the code for testing should be separated from the code needed to use it. That's what i would like to be able to put it in files that i can define in my kitchen.yml.

Do you completely disagree with this evolution, or if someone code it and make a PR it could be accepted?

**Comment by ek9** [comment]
Yeah, but what prevents you from having a `tests` directory for this? Your original request was to use `states_from_file`, which is possible (that's the name of tihs issue). If you don't want to use the files, then you can define states directly in `.kitchen.yml` file.

I believe all the functionality that you need is already there so I can't coment on the PRs or what it would do additionally. Perhaps we are missing something and you could explain better?

**Comment by gtmanfred** [comment]
I am closing this issue in favor of #92 which contains more information.
