### ISSUE TITLE
Remove relying on chef bootstrap script by default

### ISSUE THREAD

**Issue by ek9** [saltstack/kitchen-salt#90]
I've opened an issue as I would like to discuss if it's necessary to have `chef` boostrap script by default? To me this caused a bit of confusion and I've done some PRs when I realised that only ruby and gems is required.

I've noticed this was also discussed on separate issues (e.g. #71 ), but as I did not want to start asking questions / giving input on unrelated issue, I thought a separate one might be worth.

My suggestion would be to not use `chef` bootstrap script by default and switch to at least using `assets/install.sh`. I've seen that people already mentioned on #71 that they would like to drop the `chef` requirements and I would strongly agree with this.

Main reason why I am suggesting it is:
- Salt has support on a lot of different platforms. A lot more than chef. Attaching this formula to chef directly, limits on what OS this cna be run at.

My suggestion:
- Remove chef bootstrap script from defaults
- Make sure out `assets/install.sh` script supports all the platforms we aim to support. I did a few PRs and can do a few more if we have a list of platforms we want to support before the switch.

**Comment by daks** [comment]
As this software is used to enable use of Salt in Kitchen, most users don't need Chef, so by default its installation could be disabled. Eventually an option to enable it could be useful.

**Comment by cmarzullo** [comment]
👍 I'd love to get rid of the chef step.

**Comment by ek9** [comment]
I have an idea that could be helpful and wouldn't break any backwards compatiblity:

1. We set the default script to `assets/install.sh` and make sure to maintain it.
2. In `assets/install.sh`, if that file cannot find any defined platform, it could fallback to using the chef's installer.

The link to a current chef's installed can always be documented and anyone needing this would be free to choose using it.

Question is, do we need to fallback to use the chef or not? Is there at least someone depending on `chef` being actually installed by this formula, that could share on why it's needed?

**Comment by simonmcc** [comment]
@ek9 this sounds good to - want to make a PR for that?

**Comment by ek9** [comment]
Happy to! I will sort this out later today.

**Comment by ek9** [comment]
A bit lat, but PR is in :)
