### ISSUE TITLE
Improving documentation

### ISSUE THREAD

**Issue by ek9** [saltstack/kitchen-salt#91]
Current Project's documentation is split among these files:

- `README.md` - general info
- `INTRODUCTION.md` - introduction on how to use
- `provisioner_options.md` - provisioner options
- `docs` folder contains some examples/samples for `ruby/tinhat` (I believe this one is a bit unmaintained)

I believe this sort of structure / split of things ony makes it difficult for someone to start using `kitchen-salt`. There have been a few relevant issues when users can't find something in the documentation.

This issue's goal is to sort out project documentation so it's in one place. Possible solutions:

- **solution 1**. Leave basic information in `README.md` and then move the rest to `Wiki` (usually it's best to keep guides / tutorials in Wiki). However, small downside of that that the maintenance of the wiki separate and it's easier for wiki to get outdated as people usually only do PRs and don't update the Wiki.
- **solution 2**. Leave basic information in `README.md`, then move the rest of `.MD` files to `docs` folder where we could structure documentation. The upsides of this is that documentation is versioned together with the code. Additionally, we would be able to setup Github Pages and point it to `docs/` folder in the future, should you want to start using Github Pages for the project.

I would suggest to go with **solution 2** and I could submit a basic PR to move the files there + add basic Index / structure.

Please let me know what you think. It's a great project and I would like to improve it's documentation.

**Comment by daks** [comment]
I agree with the need of better doc, and solution 2 :)

**Comment by ek9** [comment]
I will have a look during the coming days, to see if I can do a simple PR to demonstrate solution 2. I will only focus on improving the general structure first, while keeping as much information intact.

We should consider sorting out (merging/reviewing) these PRs before we proceed with this, as it might make them conflict with the changes we do. If these look good / ready, we should preferably merge them before doing documentation update:
- #89 
- #81 
- #78 - is a bigger PR that I wouldn't like to break due to this. Also brings some nice new features that include documentation update.
- #75

**Comment by epcim** [comment]
I have niche examples I would like to add/link in documentation. We are currently migrate all https://github.com/salt-formulas to use kitchen-salt + travis for CI.

**Comment by simonmcc** [comment]
FWIW, I think option 2 is the best (it's the way I prefer to maintain docs - in sync with the code, not in a stale wiki), I've merged #89 & #81, #75 & #78 need a little rework after the other merges.

**Comment by holmboe** [comment]
FWIW I found https://github.com/ssplatt/salt201 to be a very good guide to at using kitchen-salt with Vagrant and Virtualbox. Perhaps the README could link to that instead of the current TODO that is in there? IMO the second TODO regarding ec2 is a nice to have, not a must have, so that could be removed from the README if you ask me.

**Comment by gtmanfred** [comment]
I have cleaned up the docs with a full walkthrough on getting started.

I am going to be adding some more, but I think that is a good enough start to go ahead and close this.

https://kitchen.saltstack.com
